# Generated by Django 5.0 on 2024-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pro_expiry_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_type',
            field=models.CharField(choices=[('F', 'FRESS'), ('M', 'MONTHLY'), ('Y', 'YERALY')], default='FREE', max_length=100),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
