# Generated by Django 5.0 on 2024-01-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0004_userprofile_is_pro_userprofile_pro_expiry_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_pro',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pro_expiry_data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_type',
        ),
    ]
