# Generated by Django 5.0 on 2024-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
