# Generated by Django 5.0 on 2024-01-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0009_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='profileimage/'),
        ),
    ]
