# Generated by Django 5.0 on 2024-01-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0010_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/images/default/image.jpg', upload_to='profileimage/'),
        ),
    ]
