# Generated by Django 5.0 on 2024-01-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0011_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='profileimage/'),
        ),
    ]
