# Generated by Django 5.0 on 2024-01-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
