# Generated by Django 5.0 on 2024-01-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0014_product_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='sub',
        ),
    ]
