# Generated by Django 5.0 on 2024-01-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0015_rename_product_sub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub',
        ),
    ]
